# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Peter Gee
tagline:          'Software Engineer'
description:      'Software engineer studying computer science at <a href="https://unwsp.edu/" target="_blank">UNWSP</a>'
url:              http://www.petergee.dev

author:
  name:           'Peter Gee'

paginate:         5

excerpt_separator: "<!--more-->"

# Collections
collections:
  projects:
    output: true
  
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag