# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Peter Gee
tagline:          'Software Engineer'
description:      'Software engineer studying computer science at <a href="https://unwsp.edu/" target="_blank">UNWSP</a>'
url:              http://www.petergee.me
baseurl:          /

author:
  name:           'Peter Gee'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
linkedin:
  url:           https://www.linkedin.com/in/peterggee/
  
plugins:
  - jekyll-gist
  - jekyll-paginate
